steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/client', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/legend-mama/production/client']