steps:
# build docker image using Dockerfile
- name: 'kaniko-project/executor'
  args:
  - --context=dir:///client
  - --destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
  - --cache=true

substitutions:
  _LOCATION: us-central1
  _REPOSITORY: production
  _IMAGE: client